// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmkuzxogwgxuhoizimkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdta3V6eG9nd2d4dWhvaXppbWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjE1NzQsImV4cCI6MjA2NzI5NzU3NH0.6HAWV78Dk5YCl_p-JTl2FB5aW-gQcrq4QI-DbGlPOs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});